### ISSUE TITLE
Deprecate DATASET_SUBMISSION.md

### ISSUE THREAD

**Issue by jiaqima** [Graph-Learning-Benchmarks/gli#462]
**Is your feature request related to a problem? Please describe.**
We should remove DATASET_SUBMISSION.md in favor of the up-to-date wiki page.

**Describe the solution you'd like**
Remove DATASET_SUBMISSION.md and update CONTRIBUTING.md accordingly.

**Describe alternatives you've considered**
Should we also move CONTRIBUTING.md to wiki?

**Comment by xingjian-zhang** [comment]
We may also want to deprecate the `.hjson` file in `templates/dataset-folder`. It may confuse contributors since we expect contributors to use function-based interface to create these files automatically. And, in general, we would like to hide these technical details as much as possible to reduce reading burden.

**Comment by xingjian-zhang** [comment]
In addition, we should deprecate unnecessary markdown files and move all instructions to wiki to reduce reading burden and maintenance cost. In the long run, I think we should migrate all the document on GitHub into our sphinx document (an all-in-one version).
